# Generated by Django 5.2.1 on 2025-05-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=20, verbose_name="Тема")),
                ("text_letter", models.TextField(verbose_name="Текст письма")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_send_data",
                    models.DateTimeField(
                        auto_now=True, verbose_name="дата первой отправки"
                    ),
                ),
                (
                    "last_send_data",
                    models.DateTimeField(
                        auto_now=True, verbose_name="дата последней отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("завершена", "Завершена"),
                            ("создана", "Создана"),
                            ("запущена", "Запущена"),
                        ],
                        default="создана",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="newsletters.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipient",
                    models.ManyToManyField(
                        to="newsletters.recipient", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["id"],
            },
        ),
    ]
